### ISSUE TITLE
Git Workflow

### ISSUE THREAD

**Issue by erikbarzdukas** [IsItNormal/IsItNormal#22]
Let's create a development branch that we develop against, reserving master for stable releases that could be deployed. 

Thoughts?

**Comment by andrewrweber** [comment]
Sounds great. Let's do it.

**Comment by erikbarzdukas** [comment]
Does the current state of the master branch reflect the bleeding edge of dev work on the site? I'm not sure if @kateEcobb's front end work was rolled in to it.

**Comment by erikbarzdukas** [comment]
Created the branch development
